### ISSUE TITLE
Missing selection_foreground from all themes

### ISSUE THREAD

**Issue by rlerdorf** [dexpota/kitty-themes#10]
I wrote a little command-line script to preview and switch between themes on the fly via a `kitty @ set-colors` command. However, because none of these themes set the `selection_foreground` colour the selection foreground colour leaks from the initial theme to the rest. Was it not set for a reason?

**Comment by dexpota** [comment]
I am not sure but probably the original themes didn't define the foreground color for the selection. I could set that value to `foreground` if missing. I am going to look into it.
