### ISSUE TITLE
New preview script

### ISSUE THREAD

**Issue by dexpota** [dexpota/kitty-themes#11]
Create a preview script in bash that shows you all themes (or most of them) at the same time and let you choose one. 

A nice start could be the script created by @rlerdorf which can be found [here](https://github.com/dexpota/kitty-themes/issues/1#issuecomment-509479028). The following image is a preview of the output of this script.

![kitty-kc](https://user-images.githubusercontent.com/54641/60858412-0ff63880-a1c3-11e9-967d-1f4eefe1976c.png)

**Comment by rlerdorf** [comment]
It looks a bit better after fixing the lack of `selection_foreground` in the themes:
![kc2](https://user-images.githubusercontent.com/54641/60888861-879c8580-a20c-11e9-9b9e-22151ea0f984.png)
It shows the cursor colour, the name of the theme in the `foreground` colour, the 16 colours and then a block of `selection_foreground` on top of `selection_background`
