### ISSUE TITLE
Kitty creates broken theme.conf

### ISSUE THREAD

**Issue by TeslaNguyen** [dexpota/kitty-themes#14]
Hi!

`ln -s ./kitty-themes/themes/Floraverse.conf ~/.config/kitty/theme.conf` or in my case
`ln -s ./kitty-themes/themes/Solarized_Dark_-_Patched.conf ~/.config/kitty/theme.conf` creates a broken `theme.conf`

What can I do?

Cheers

**Comment by Luflosi** [comment]
A bit more information would be nice. You could have mentioned that `ln -s ./kitty-themes/themes/Floraverse.conf ~/.config/kitty/theme.conf` is from the `README.md` file. Did you follow the three installation steps in https://github.com/dexpota/kitty-themes#source-code exactly? What exactly is "broken" about `theme.conf`?
Following the three steps works for me.

**Comment by TeslaNguyen** [comment]
I followed these exact steps, yes, only that I have substituted `Floraverse` for `Solarized_Dark_-_Patched` (the theme I'd actually like to install).

I can't tell you what is broken about `theme.conf` exactly, but here's what it looks like.

![Screenshot from 2019-08-12 23-11-38](https://user-images.githubusercontent.com/53797385/62898771-9835a380-bd56-11e9-9e29-27dbd5049db1.png)
![Screenshot from 2019-08-12 23-11-54](https://user-images.githubusercontent.com/53797385/62898772-9835a380-bd56-11e9-9de0-ca6a8834d6fb.png)

**Comment by Luflosi** [comment]
If the link is broken, it means, that the file it points to, doesn't exist.
Are you sure, that the `kitty-themes` directory is in `~/.config/kitty`? The full path should be: `~/.config/kitty/kitty-themes`. Also please double-check, that `theme.conf` is also in `~/.config/kitty`.

**Comment by TeslaNguyen** [comment]
I've added two screenshots for you to verify the locations.

![Screenshot from 2019-08-12 23-20-05](https://user-images.githubusercontent.com/53797385/62899345-dda6a080-bd57-11e9-9907-a59c40d1e22f.png)
![Screenshot from 2019-08-12 23-20-48](https://user-images.githubusercontent.com/53797385/62899346-de3f3700-bd57-11e9-8e4e-8575d9038a70.png)

**Comment by TeslaNguyen** [comment]
I just noticed that `theme.conf` is reffering to /kitty-themes/themes, how did I miss that?

**Comment by Luflosi** [comment]
You probably meant `./kitty-themes/themes`, right? The `.` is important. Starting the path with a `/` means that it is an absolute path, which is different from a relative path. Alternatively you can also leave out the `./`, which should work just as well when symlinking.
Either create a `themes` directory inside `kitty-themes` or use `ln -s ./kitty-themes/Solarized_Dark_-_Patched.conf ~/.config/kitty/theme.conf` (without the `themes`).
You could also not use a symlink at all and specify the path to the config file directly in `kitty.conf`. The symlink is just for convenience.

**Comment by TeslaNguyen** [comment]
I did just that, create `themes` in `kitty-themes` and moved `Solarized_Dark_-_Patched.conf ` there; `theme.conf` is now a working file, however the theme per se is still not being applied in the kitty terminal.

Does `include ./theme.conf` have to go somewhere else?

![Screenshot from 2019-08-12 23-38-18](https://user-images.githubusercontent.com/53797385/62900402-54dd3400-bd5a-11e9-8054-d1a43c65de19.png)

**Comment by Luflosi** [comment]
Remove the `#` and space in front. That tells kitty, that everything after that is just a comment and should be ignored. You also have to restart kitty for the changes to take effect.

**Comment by Luflosi** [comment]
I recommend to put that line at the very bottom, so that there are no settings that might override the settings in the theme.

**Comment by TeslaNguyen** [comment]
> Remove the `#` and space in front. That tells kitty, that everything after that is just a comment and should be ignored. You also have to restart kitty for the changes to take effect.

That worked! I've only added the # because I was quite sure it said that it had to be there, my mistake.

It's working now, thank you very much!

**Comment by Luflosi** [comment]
You're welcome.
I see now, this is an issue in the documentation. When following the instructions under `or download just one theme:`, the symlink in step two is broken, as described in this issue. I followed the alternative instructions above, which work correctly. I'll make a pull request to add the `themes` directory to the download path. You can keep this issue open until it's merged.

**Comment by TeslaNguyen** [comment]
Sounds good. Thank you again and have a great evening, I really appreciate you taking the time to help me out with this!
