### ISSUE TITLE
Solarized_light doesn't maintain contrast of the first 16 terminal colors

### ISSUE THREAD

**Issue by BlueDrink9** [dexpota/kitty-themes#17]
This breaks hint highlighting

color0 should be the background and color7 should be the foreground and color 15 should be the intense foreground

[See here for an explanation](https://github.com/kovidgoyal/kitty/issues/541)

**Comment by BlueDrink9** [comment]
Awesome work, thanks very much!

**Comment by BlueDrink9** [comment]
The hint text isn't perfect now, but they're definitely better. Actually visible, if barely.

**Comment by dexpota** [comment]
I used `#eee8d5` as the intense foreground color. Now that I am thinking about it maybe is not the right one to choose, `#586e75` could be the correct one to use.

**Comment by dexpota** [comment]
I think I am going to change it to`#586e75`, it is the same color used for emphasized content by Solarized Light.

![Screenshot 2019-08-21 13:16:29](https://user-images.githubusercontent.com/7031675/63427690-055fcd80-c416-11e9-9ce0-dda85d54b9c1.png)

**Comment by BlueDrink9** [comment]
Brilliant work, that looks fantastic. Thank you!

**Comment by BlueDrink9** [comment]
37d1a52 didn't change it to #586e75, were you intending to?

**Comment by dexpota** [comment]
Sorry, my bad.

But there is one thing I don't quite get, according to the ANSI codes `color0` should be a "black" color and `color7` a "white" one. I am not sure that kitty does the right thing by using the white color to emphasize URLs, maybe should use the `foreground` color with a bold text.

**Comment by BlueDrink9** [comment]
Mmm, that's an interesting point. I agree, I was also struggling to figure that out. Maybe reply to Kovid on the issue I mentioned above?

Does kitty use 7 or 15 for hints?

**Comment by dexpota** [comment]
It uses `color15`
