### ISSUE TITLE
Solarized_light: background not correct

### ISSUE THREAD

**Issue by BlueDrink9** [dexpota/kitty-themes#18]
[Original solarized](https://ethanschoonover.com/solarized) uses `#fdf6e3` as the background, whereas this theme has `#fcf4dc`.

**Comment by dexpota** [comment]
Thank you for your feedback. 

I fixed the issue with the background color, now it seems to me that other values on the theme configuration are not correct, like foreground which should be `#839496` but its `#52676f`.

**Comment by BlueDrink9** [comment]
Aah, interesting. Where was the theme from originally?
Would you consider updating all of the theme values to their correct solarized values?

**Comment by dexpota** [comment]
I imported the themes from [iTerm2-Color-Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes) at the time they didn't have kitty configuration files.

I am definitely going to fix the theme color scheme, I opened an issue #19
