### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by scopatz** [dexpota/kitty-themes#5]
So there is a tarball to download.  This helps packagers of these themes.  Thanks!

**Comment by dexpota** [comment]
At the moment there is no tarball to download, I will make one as soon as possible (probably today). Thank you for your suggestion.

**Comment by scopatz** [comment]
Thanks so much @dexpota! I really appreciate it.

Also, I was saying that if you push up a tag, GitHub will automatically generate a tarball for you, so you don't even need to generate one manually, if you don't want.

**Comment by dexpota** [comment]
I didn't know of this feature. I have just pushed a tag, now you can find the tarball to download.

**Comment by scopatz** [comment]
Thanks!
