### ISSUE TITLE
cannot pull themes

### ISSUE THREAD

**Issue by tjallemaal** [dexpota/kitty-themes#56]
when I try to pull via
`git clone --depth 1 git@github.com:dexpota/kitty-themes.git ~/.config/kitty/kitty-themes`
 I get an error:

```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

**Comment by Lraxer** [comment]
1. Please make sure you can [connect to Github with SSH](https://docs.github.com/en/authentication/connecting-to-github-with-ssh). Using https could be easier.

```
git clone https://github.com/dexpota/kitty-themes.git
```

2. If you prefer using SSH, and you have added a SSH key to Github correctly, maybe this is helpful. https://github.com/docker-library/golang/issues/148#issuecomment-355082955

**Comment by dexpota** [comment]
Like @Lraxer said, you have to either add an SSH key or use the HTTPS URL. To simplify the instructions, I am going to update the README file to use the HTTPS URL instead of the SSH one.
